export const QUEUES = {
  EMAIL_QUEUE: 'EmailQueue',
};

export const JOBS = {
  SEND_EMAIL: 'sendEmail',
};

export const FILE_LIMITS = {
  DBA_FILE_LIMIT: 10,
  CP_PAST_PERFORMANCE_LIMIT: 10,
  CP_PRODUCTS_AND_SERVICES_FILE_LIMIT: 10,
};

export const MAX_DBA_FILE_SIZE_MB = 50;
export const MAX_DBA_FILE_SIZE_BYTES = MAX_DBA_FILE_SIZE_MB * 1024 * 1024;

export const MAX_CP_PRODUCT_AND_SERVICES_FILE_SIZE_MB = 500;
export const MAX_CP_PRODUCT_AND_SERVICES_FILE_SIZE_BYTES = MAX_CP_PRODUCT_AND_SERVICES_FILE_SIZE_MB * 1024 * 1024;

export const MAX_CP_PRODUCT_OR_SERVICES_IMAGE_SIZE_MB = 5;
export const MAX_CP_PRODUCT_OR_SERVICES_IMAGE_SIZE_BYTES = MAX_CP_PRODUCT_OR_SERVICES_IMAGE_SIZE_MB * 1024 * 1024;

export const MAX_FILE_SIZE_MB = 50;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

export const MAX_PAST_PROFORMANCE_FILE_SIZE_MB = 50;
export const MAX_PAST_PROFORMANCE_FILE_SIZE_BYTES = MAX_PAST_PROFORMANCE_FILE_SIZE_MB * 1024 * 1024;

export const MAX_CP_AWARDS_FILE_SIZE_MB = 500;
export const MAX_CP_AWARDS_SIZE_BYTES = MAX_CP_AWARDS_FILE_SIZE_MB * 1024 * 1024;
